# pyproject.toml
[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "saferoad"
version = "0.1.0"
description = "Road network safety analysis using Multi Temporal InSAR and road network data"
authors = [{ name = "Murat Sahin", email = "m.sahin@tudelft.nl" }]
readme = "README.md"
requires-python = ">=3.10"
dependencies = ["matplotlib", "duckdb", "shapely", "contextily", "tqdm"]

[tool.setuptools.packages.find]
where = ["src"]
